### ISSUE TITLE
Run missed jobs if the server was down

### ISSUE THREAD

**Issue by jitowix** [rschmukler/agenda#157]
I need to run a job every week (monday at 8:30am) to reset some data from my database.
If the server was down at this time and come back online at 9am, how can I force the missed job to run?

**Comment by droppedoncaprica** [comment]
Generally speaking, the job will run on initial Agenda startup if it is set via human interval and will run only  at the specific time if set via the `cron` syntax.

Overall, I don't think there's a way currently of re-running missed jobs.  Say if a job was supposed to run every day at noon and the server was down for a week, the server won't re-run the jobs that were missed when it gets brought back up.

**Comment by jitowix** [comment]
Thanks, I've switched to human interval and this seems to work.

**Comment by droppedoncaprica** [comment]
Awesome, glad that fixed it for you.

**Comment by adrian-gierakowski** [comment]
I have the same issues, however I don' think that switching to human interval is a suitable solution. I can't figure out how to make the job run reliably at specific time of day ( for example at 4:15 am  each day ) using human interval.

Problem 1:
when a new job with human interval is added it will execute immediately after agenda starts.
Problem 2: 
even if its possible to solve problem 1, the job will time will drift if the job is missed due to server being down. This is due to the fact that time of next run is calculated based on the actual time the most recent run occurred ( example: job was supposed to run at 9am, but was actually ran at 9:30am, next job will be scheduled for 9:30am the following day not 9am).

@cwagner22 how have you achieved your desired outcome?

I have managed to make the most recently missed cron job to be ran when agenda starts by changing one line of code:
https://github.com/adrian-gierakowski/agenda/commit/ce78a114293080d375aba659963ac5832ce802c6

not sure if it breaks any other functionality but all tests pass. I could add a test case for this feature and make a pull request there is a chance that it would be accepted

best

**Comment by cwagner22** [comment]
@adrian-gierakowski I can't really help you as I haven't used node.js for quite some time now. I'm currently using rails and there is a library called `sidekiq` which works well for reliably handling background tasks with the help of redis. Maybe there is something like that for node.js

However I'd assume that using `job.repeatAt('9:00am');` would work even if the first job was delayed...

My 2 cents.
